version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  pine-valley-hospital:
    build:
      context: ./pine-valley-hospital
    container_name: pine-valley-hospital
    environment:
      KAFKA_BROKER: kafka:9092
      REQUEST_TOPIC: request-topic
      RESPONSE_TOPIC: response-topic
      GROUP_ID: pine-valley-hospital-group
    depends_on:
      - kafka

  grand-oak-hospital:
    build:
      context: ./grand-oak-hospital
    container_name: grand-oak-hospital
    environment:
      KAFKA_BROKER: kafka:9092
      REQUEST_TOPIC: request-topic
      RESPONSE_TOPIC: response-topic
      GROUP_ID: grand-oak-hospital-group
    depends_on:
      - kafka

  aggregate-hospital:
    build:
      context: ./aggregate-hospital
    container_name: aggregate-hospital
    environment:
      KAFKA_BROKER: kafka:9092
      REQUEST_TOPIC: request-topic
      RESPONSE_TOPIC: response-topic
      GROUP_ID: aggregate-hospital-group
    ports:
      - "5000:5000"
    depends_on:
      - grand-oak-hospital
      - pine-valley-hospital
      - kafka
